In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
print(tf.__version__)

2.0.0


In [2]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

#index
print(t)
print(t[:, 1:])
print(t[..., 1])

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [4]:
print(t[:, 1])

tf.Tensor([2. 5.], shape=(2,), dtype=float32)


In [5]:
# operators
print(t + 10)
print(tf.square(t))
print(t @ tf.transpose(t))

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [6]:
#numpy conversion
print(t.numpy())
print(np.square(t))
np_t = np.array([[1., 2., 3.], [4., 5., 6.]])
print(tf.constant(np_t))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [8]:
#Scalars
t = tf.constant(2.1)
print(t.numpy())
print(t.shape)

2.1
()


In [9]:
# strings
t = tf.constant('cafe')
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t, unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t, 'UTF8'))

tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [10]:
# strings array
t = tf.constant(['cat', '猫'])
print(tf.strings.length(t, unit='UTF8_CHAR'))
r = tf.strings.unicode_decode(t, 'UTF8')
print(r)

tf.Tensor([3 1], shape=(2,), dtype=int32)
<tf.RaggedTensor [[99, 97, 116], [29483]]>


In [11]:
# ragger tensor
r = tf.ragged.constant([[11, 22], [33,], [], [55, 66, 77]])
# index
print(r)
print(r[1])
print(r[1:2])

<tf.RaggedTensor [[11, 22], [33], [], [55, 66, 77]]>
tf.Tensor([33], shape=(1,), dtype=int32)
<tf.RaggedTensor [[33]]>


In [15]:
# ops on ragged tensor
r2 = tf.ragged.constant([[51, 52], [], [53]])
print(tf.concat([r, r2], axis=0))

<tf.RaggedTensor [[11, 22], [33], [], [55, 66, 77], [51, 52], [], [53]]>


In [16]:
r3 = tf.ragged.constant([[51, 52], [], [53], [16,20]])
print(tf.concat([r, r3], axis=1))

<tf.RaggedTensor [[11, 22, 51, 52], [33], [53], [55, 66, 77, 16, 20]]>


In [17]:
print(r.to_tensor())
print(r.to_list())

tf.Tensor(
[[11 22  0]
 [33  0  0]
 [ 0  0  0]
 [55 66 77]], shape=(4, 3), dtype=int32)
[[11, 22], [33], [], [55, 66, 77]]


In [2]:
# sparse tensor
# indices should be written in order, otherwise would cause bug when call to_dense()
# if wrong order, use sparseTensor = tf.sparse.reorder(sparseTensor)
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
print(s)
print(tf.sparse.to_dense(s))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


In [8]:
# ops on sparse tensor
s2 = s * 2.0
print(s2)

try:
    s3 = s + 1.
except TypeError as ex:
    print(ex)

s4 = tf.constant([[10, 20],
                  [30, 40], 
                  [50, 60], 
                  [70, 80]], dtype=float)
print(tf.sparse.sparse_dense_matmul(s, s4))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
unsupported operand type(s) for +: 'SparseTensor' and 'float'
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]], shape=(3, 2), dtype=float32)


In [15]:
# tf Variables
v = tf.Variable([[1., 2., 3.], [4., 5., 6.,]])
print(v)
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
# assign value
v.assign(2*v)
print(v.numpy())
v[0, 1].assign(13)
print(v.numpy())
v[1].assign([5, 5, 4])
print(v.numpy())

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 2. 13.  6.]
 [ 8. 10. 12.]]
[[ 2. 13.  6.]
 [ 5.  5.  4.]]


In [17]:
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment
